### ISSUE TITLE
Kullanıcıyı takip ederken onay mesajı gereksiz.

### ISSUE THREAD

**Issue by shibby** [miratcan/resmin#109]
Bu konu biraz gereksiz gibi. tıklayınca direkt takip etse ne olacak? neden takip et dedikten sonra onaylamak zorundayım ki. silmiyoruz sonuçta.

**Comment by miratcan** [comment]
Çok gıcık olduğun birine yanlışlıkla takip talebi yolladın diyelim? Hop emin misin diye sorması iyi değil mi? Bir çok kişi instagram ve twitter'da birini stalk ederken yanlışlıkla like ettiğinden falan bahsediyor.

**Comment by shibby** [comment]
Abi instagram bu isi bilerek yapiyor. İnsanlarin yanlislikla like etmesi
icin elinden geleni yapiyor. İnteraksiyonu arttirmak icin tabiki.
Ben kullanimin daha kolay olcagini dusunuyorum. Cunku zaten interaksiyonu
arttirmak gibi bi amacimiz yok ve cok kolaylikla yanlis tiklama yapilacak
bir konu degil.
21 Şub 2015 15:56 tarihinde "Mirat Can Bayrak" <notifications@github.com>
yazdı:

**Comment by miratcan** [comment]
Hacı bu iş şimdilik kalsın bi sürü değişikliğe ihtiyaç olacak. İlerde tekrar açarız belki.
