### ISSUE TITLE
Login olmamış kullanıcı için Yorum yapma formu gözüküyor, gözükmemeli.

### ISSUE THREAD

**Issue by miratcan** [miratcan/resmin#115]

**Comment by bahattincinic** [comment]
Bunu ben duzeltirim.

**Comment by miratcan** [comment]
Güzel olur :)

**Comment by bahattincinic** [comment]
Tammamdir. Vakit buldukca diger issue larina da bakar yardimci olurum sana.

**Comment by miratcan** [comment]
Pekala bu işe dokunmuyorum, pull requestini beklemekteyim :)

**Comment by miratcan** [comment]
@bahattincinic buna bakabilecek misin ben gireyim mi?

**Comment by bahattincinic** [comment]
Unutmusum ben bunu :smile:  bugun gonderiyorum PR
