### ISSUE TITLE
Requirements listesinde django-pipeline versionu yanlış gözüküyor.

### ISSUE THREAD

**Issue by miratcan** [miratcan/resmin#124]
Dün @rkirmizi  bu version ile çalıştıramadı, 1.3.17'ye çekti öyle çalıştı. Yanlış bir şey yapmış olabilir miyiz?

**Comment by rkirmizi** [comment]
atla deve bir durum yok aslında. Çağırdığın template taglarını güncelleyeceksin. [1] adresinde anlatılmış.

Update templates to use the new syntax
{# pipeline<1.4 #}
```
{% load compressed %}
{% compressed_js 'group' %}
{% compressed_css 'group' %}
```
{# pipeline=1.4 #}
```
{% load pipeline %}
{% javascript 'group' %}
{% stylesheet 'group' %}
```

Add the PipelineFinder to STATICFILES_FINDERS
```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)
```
[1] https://django-pipeline.readthedocs.org/en/latest/installation.html#upgrading-to-1-4

**Comment by miratcan** [comment]
Düzelttim.

**Comment by rkirmizi** [comment]
commit'leri yaparken neden iş kaydına referans vermiyorsun?
