### ISSUE TITLE
Dosya upload ederken, maksimum dosya boyutu aşılırsa kullanıcının haberi olmuyor.

### ISSUE THREAD

**Issue by miratcan** [miratcan/resmin#126]
Gönderi donuyor kalıyor öyle.

**Comment by rkirmizi** [comment]
model'de exception'i yakalamissin. view de kontrol etmiyor musun?

https://github.com/miratcan/resmin/blob/master/resmin/apps/story/models.py#L367

**Comment by miratcan** [comment]
Aynen, view'da bu exception oluştu ise bir error responsu dönmek lazım.

**Comment by miratcan** [comment]
Fixledim.
