### ISSUE TITLE
Cevap iste, kısmında açıklamalar yetersiz.

### ISSUE THREAD

**Issue by barantr90** [miratcan/resmin#138]
cevap iste kısmı çalışmıyor.
- Açıklama kısmı hatalı olabilir
- Açıklama eksik olabilir
- Gerçekten fonksiyon çalışmıyor olabilir

yazan açıklama: Questionees (Cevap isteyen kişilerin kullanıcı adını virgüllerle ayırarak yaz)
denediğim kombinasyonlar;
- baransengul
- @baransengul
- baransengul,
- @baransengul,

hepsinde aldığım hata: kullanıcı bulunamadı

**Comment by miratcan** [comment]
Spama bağlamasın kimse diye cevap isteyebildiğin kişileri sadece [seni takip eden kişiler](https://github.com/miratcan/resmin/blob/master/resmin/apps/question/forms.py#L51) olarak belirledim. Kendi kendini follow etmediğinden dolayı cevap etmediğin için işe yaramayacaktır. http://resm.in/u/baransengul/followers/ buradaki kişilerin username'ini denediğinde işe yaramıyor mu?

**Comment by barantr90** [comment]
Tamam beni takip eden kişilerden birinin adını yazdığımda çalışıyor(sana da zaten bildirim gelmiştir) ama bu durumunda düzeltilmesi gerek. Ya açıklama kısmında belirtmeli ya da(ki bence olması gereken) 'Cevap istediğinizi kullanıcıyı takip etmediğiniz için gerçekleştiremiyoruz' tarzı bir yazı olmalı.

**Comment by miratcan** [comment]
Haklısın, düzgün bir açıklama gerekli oraya. İşin başlığını değiştiriyorum.
