### ISSUE TITLE
Bir soruda yanıt görüntülerken, diğer yanıtlar

### ISSUE THREAD

**Issue by shibby** [miratcan/Resmin#144]
Bir soruda yanıt görüntülerken, diğer yanıtları da görebilmeliyiz. Sağ-sol tuşlarıyla önceki sonraki yanıta gidebilmeliyiz. En olmadı bir yerde küçük resimler olmalı diğer yanıtları belirten. Ama navigasyon önemli bak. Sağ sol.

**Comment by miratcan** [comment]
Bana bug report et adam.

**Comment by miratcan** [comment]
Eklendi.
