### ISSUE TITLE
Anonim cevaplar tahmin edilebilir.

### ISSUE THREAD

**Issue by shibby** [miratcan/resmin#145]
Anasayfada "Duvar" gösteriminde, sanırsam sadece takip ettiğimiz kişilerin resimleri gösteriliyor. Peki buraya yorum yapmış olduğu resimler de dahil mi? 
eğer yorum yaptıkları dahil değil, sadece kendi paylaştıkları görüntüleniyorsa, ayıpçı resimlere ne oluyor?

**Comment by miratcan** [comment]
Yorum yapmış olduğu resimler dahil değil. Anonim resimlere ne oluyor diyecektin sanırım oradaki mantık sorunlu. Eğer 5 kişiyi takip ediyorsan aralarında br kişi anonim  resminlerse kim olduğunu tahmin edebiliyorsun böyle olmamalı...

Çözüm olarak Anonymouse adında gerçek bir kullanıcı oluşturacağım eğer anonim paylaşsın dersek o kullanıcı tarafından paylaşılacak. O kullanıcıyı takip edenler görecek. Böylelikle kimin cevapladığı tahmin edilemez olacak...

**Comment by shibby** [comment]
Evet dediğin gibi tahmin ettim kim olduğunu ondan açtım bunu :(

Anonymouse kullanıcı mantıklı bir olay. ffanony gibi. Sevdim.

Bu arada yorum yapılmış resimler konusunu tartışmak istiyorum. Buradan mı tartışalım yeni bir issue mi açalım?

**Comment by aligundogdu** [comment]
Buradan devam etmekte fayda var konu paralellik gösteriyor.

**Comment by miratcan** [comment]
Bunu tamamen erteliyorum Anonim gönderiler iptal oluyor, API çıkınca birisi yazar harici uygulama olarak.
