### ISSUE TITLE
Yorumlarda güvenlik açığı.

### ISSUE THREAD

**Issue by barantr90** [miratcan/resmin#154]
HTML, script vb. kodlardan datanı ayıklamıyorsun.
Yorum kısmına istediğim dilde kod yazıp çalıştırabiliyorum. Bu çok büyük bir güvenlik açığı.
Örneklerini de aşağıda paylaşıyorum.

![jquery](https://cloud.githubusercontent.com/assets/5478485/6802396/bbd9e0ca-d238-11e4-91a9-d2b515763944.jpg)

```
<script>alert('Merhab Dünya!')</script>
```
![redirect](https://cloud.githubusercontent.com/assets/5478485/6802397/bbdaac26-d238-11e4-8f90-450dece878a6.jpg)

Dip not: Kullanıcıya asla güvenme :+1:

**Comment by miratcan** [comment]
Olm ben sizi dost bilmiştim fskdsl

**Comment by barantr90** [comment]
:smile: 
- Django kesin çok basit şekilde dataları output ederken escape ediyordur.
- Bana sorarsan da dataları daha kayıt etmeden escape et mümkün mertebe DB'de temiz data kalsın. Ben öyle yapıyorum projelerimde.
- Son olarak... Hacklerin heee :sweat_smile:

**Comment by shibby** [comment]
Mirat bunu hala düzeltmedin mi sen?
