### ISSUE TITLE
Soruların link fotoğrafı seçilebilir olmalı.

### ISSUE THREAD

**Issue by miratcan** [miratcan/Resmin#160]
Bir gönderi paylaşılırken, facebook'un croplamasından dolayı anlaşılmaz fotoğraflı gönderiler oluşuyor.

![ekran resmi 2015-03-31 12 43 25](https://cloud.githubusercontent.com/assets/140968/6916535/bc00b44e-d7a5-11e4-990c-2e5e5d085ec7.png)

Gönderiyi oluşturan kullanıcının link fotoğrafını seçebilmesini, ve facebook twitter mecralar için kendi göz zevkine göre croplayabilmesini sağlamak gerek. 

Facebook linklerinde boyut: 470x256
Twitter kartlarında boyut: 506x253
Google plus: Aynen koruyor.

Croplama işini yapabilmek için şurada bir eklenti var, baya iyi gözüküyor:
http://fengyuanchen.github.io/cropper/

**Comment by barantr90** [comment]
Facebook open graph le bu iş aşılamıyor mu?
Şu linkleri buldum bir incele istersen.

https://developers.facebook.com/docs/sharing/best-practices#images
http://stackoverflow.com/questions/20537676/facebook-crops-open-graph-image-in-to-a-square
