### ISSUE TITLE
Mobilden gönderilen imajların thumbnailleri bozuluyor.

### ISSUE THREAD

**Issue by miratcan** [miratcan/Resmin#167]
![screen shot 2015-04-07 at 09 36 44](https://cloud.githubusercontent.com/assets/140968/7018160/a9ffd888-dd09-11e4-85d3-af0691abce92.png)

**Comment by gkmngrgn** [comment]
neden acaba, merak ettim =)

**Comment by miratcan** [comment]
sorl-thumbnail kütüphanesinde hata varmış.
