### ISSUE TITLE
imajların alt etiketi boş.

### ISSUE THREAD

**Issue by miratcan** [miratcan/Resmin#172]

**Comment by barantr90** [comment]
yalniz bundan sana daha oncede bahsetmistim. Insanlar google'da indexlenmek istemiyorlarsa bu biraz riskli.

**Comment by miratcan** [comment]
indexlenmek istemeyen private bölümünü kullansa?

25 Nisan 2015 17:49 tarihinde Baran Şengül <notifications@github.com> yazdı:

> yalniz bundan sana daha oncede bahsetmistim. Insanlar google'da
> indexlenmek istemiyorlarsa bu biraz riskli.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miratcan/Resmin/issues/172#issuecomment-96217474>.
>



-- 
http://miratcan.tumblr.com / http://github.com/miratcan/ /
http://linkfloyd.com

**Comment by barantr90** [comment]
Private bölümünün kullanımı ortada ama bence olması gereken normal olanı. Google indexleyebilir. Bunu kullanıcıların sorun etmemesi gerek.

**Comment by miratcan** [comment]
instagram indexliyor mu?

25 Nisan 2015 20:48 tarihinde Baran Şengül <notifications@github.com> yazdı:

> Private bölümünün kullanımı ortada ama bence olması gereken normal olanı.
> Google indexleyebilir. Bunu kullanıcıların sorun etmemesi gerek.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miratcan/Resmin/issues/172#issuecomment-96245703>.
>



-- 
http://miratcan.tumblr.com / http://github.com/miratcan/ /
http://linkfloyd.com

**Comment by miratcan** [comment]
http://www.google.de/imgres?imgurl=http%3A%2F%2Fresm.in%2Fstatic%2Fmedia%2Fcache%2Fb7%2Fbb%2Fb7bbaaad1491ca818cdd961e7a418fd7.jpg&imgrefurl=http%3A%2F%2Fresm.in%2Fs%2FBUO%2F&h=581&w=580&tbnid=CoH85yO1Pybr9M%3A&zoom=1&docid=ABk7RsWhgJl_ZM&ei=gdQ7Vdi6I8LSaKqVgcgM&tbm=isch&iact=rc&uact=3&dur=2353&page=1&start=0&ndsp=29&ved=0CEwQrQMwDg

burayı indexlemiş nedense

25 Nisan 2015 20:51 tarihinde Mirat Bayrak <miratcanbayrak@gmail.com> yazdı:

> instagram indexliyor mu?
>
> 25 Nisan 2015 20:48 tarihinde Baran Şengül <notifications@github.com>
> yazdı:
>
>> Private bölümünün kullanımı ortada ama bence olması gereken normal olanı.
>> Google indexleyebilir. Bunu kullanıcıların sorun etmemesi gerek.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/miratcan/Resmin/issues/172#issuecomment-96245703>.
>>
>
>
>
> --
> http://miratcan.tumblr.com / http://github.com/miratcan/ /
> http://linkfloyd.com
>



-- 
http://miratcan.tumblr.com / http://github.com/miratcan/ /
http://linkfloyd.com

**Comment by barantr90** [comment]
Bu indexleme işini araştırmak gerek. Neye göre nasıl indexliyor diye

**Comment by barantr90** [comment]
imajlara alt etiketi bence konabilir sorun yok. Google'da indexliyecekse indexlesin problem o değil ama senin imajların adları ne olacak? Alt etiketine ne basılacak o kısım önemli. Story adı olacaksa random garip bir adı olur ki bu istediğimiz bir senaryo değil. Kullanıcı adı + random bir şey olacaksa kısmen mantıklı olabilir. Asıl bu konuda düşünmek gerekiyor bence :smile:

**Comment by barantr90** [comment]
Bunu da artık kapatabilirsin bence. Fixed!

**Comment by miratcan** [comment]
:+1:
