### ISSUE TITLE
Hesap silme

### ISSUE THREAD

**Issue by miratcan** [miratcan/Resmin#173]
bu ara bu talep üst üste gelmeye başladı bunalmaya başladım. kullanıcı kendi hesabını silebilmeli.

**Comment by barantr90** [comment]
Bence silmeden ziyade dondurma tarzinda islesin sistem.
Kullanici hesabini dondurdugunda kullaniciya ait gonderiler, yorumlar ve begenmelerinde silinmesi gerek.

**Comment by miratcan** [comment]
Hesap deaktive edildiğinde:

 1) Kullanıcının is_active alanı False olarak yazılmalı.
 2) Hikayeler alınırken sadece aktif olan userlara ait olanlar getirilmeli.
 3) Yorumlar alınırken yorum yapan kişinin hesabı aktif değilse adı "silinmiş kullanıcı" olarak gözükmeli.
 4) Sevdicekler bölümünden kullanıcı kaldırılmalı.

Hesap tamamen silindiğinde:
  1) Kullanıcının kaydı silinmeli.
  2) Kullanıcıya ait hikayelere ait like tabloları silinmeli.
  3) Kullanıcıya ait hikayeler veritabanından silinmeli.
  4) Kullanıcıya ait yorumlar sistemde sahipsiz olarak kalmaya devam etmeli.
  5) Sevdicekler tablosu güncellenmeli.

**Comment by nessleekhan** [comment]
Hesabımın silinmesini istiyorum yardım edin lütfen

**Comment by miratcan** [comment]
site kapali yahu? hesap silinecek bir site yok ki ortada?

**Comment by ogomogo** [comment]
github hesabini sildirmek istiyor herhalde :)

**Comment by nessleekhan** [comment]
Evet 😑

**Comment by ogomogo** [comment]
Github hesabını silmek istiyorsan şu sayfada aşağı kısımda görünen aşamaları takip et https://help.github.com/articles/deleting-your-user-account/ Sonunda silemezsen ise buraya değil, Github'a sor direk olarak.

**Comment by miratcan** [comment]
4 senedir site kapalı?

**Comment by miratcan** [comment]
@melihmelih23 sen hasta falan misin?
