### ISSUE TITLE
Taslaklardaki gönderilerin timestamp'leri yanlış

### ISSUE THREAD

**Issue by barantr90** [miratcan/Resmin#176]
Başlıktan belki tam olarak ne dediğim anlaşılmıyor olabilir ama eğer ki bir gönderiyi taslaklara kaydetmişsen ve atıyorum iki gün sonra göndermeye karar verdiysen timeline'da iki gün öncesinde gönderilen gönderiler arasında kendine yer buluyor. Yani yayınlanma tarihi baz alınmıyor da taslaklara kaydedilme tarihi baz alınıyor.

**Comment by miratcan** [comment]
:+1:
