### ISSUE TITLE
Soru aramada ux geliştirmesi

### ISSUE THREAD

**Issue by shibby** [miratcan/Resmin#181]
[Imgur](http://i.imgur.com/mRdB7mL.png)

bulunan soru başlığına tıklayınca, doğrudan cevaplar sayfasına gitmeli. 2-3 defa tıkladım sonra farkettim. 
cevapla linkine tıklamak istemedim çünkü soruyu yanıtlamayacaktım sadece görüntüleyecektim.

**Comment by miratcan** [comment]
:+1:

**Comment by miratcan** [comment]
Bu zaten fixlenmiş ya.
